<?php

/**
 * @file
 * Contains dart_tools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

module_load_include('inc', 'dart_tools');

/**
 * Implements hook_help().
 */
function dart_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dart_tools module.
    case 'help.page.dart_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 usefull snippets and utils') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function dart_tools_form_image_style_add_form_alter(&$form, $form_state, $key) {
  // Allow to have long image style names.
  $form['name']['#maxlength']  = 255;
  $form['label']['#maxlength'] = 255;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dart_tools_form_image_style_edit_form_alter(&$form, $form_state, $key) {
  // Allow to have long image style names.
  $form['name']['#maxlength'] = 255;
  $form['label']['#maxlength'] = 255;
}

