<?php

/**
 * @file
 * Contains dart_tools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dart_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dart_tools module.
    case 'help.page.dart_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 usefull snippets and utils') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dart_tools_theme() {
  $theme = [];

  return $theme;
}
