<?php

/**
 * @file
 * Contains dart_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dart_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dart_core module.
    case 'help.page.dart_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Art core module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dart_core_theme() {
  $theme = [];

  return $theme;
}
