<?php
/**
 * @file
 *   Module hooks.
 */

use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function advanced_varnish_cache_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $id = $form['id']['#default_value'];
  $block = \Drupal\block\Entity\Block::load($id);
  if ($block) {
    $settings = $block->get('settings');
  }
  $form['settings']['cache']['esi'] = array(
    '#type' => 'checkbox',
    '#title' => t('ESI block'),
    '#default_value' => $settings['cache']['esi'] ?: FALSE,
  );
}

function advanced_varnish_cache_form_page_manager_display_variant_edit_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Get form storage.
  $storage = $form_state->getStorage();

  // Get page variant.
  $page = $form_state->getBuildInfo()['args'][0];
  $vid = $storage['display_variant_id'];
  $variant = $page->getVariant($vid);

  // Get current block from page variant.
  $bid = $storage['block_id'];
  $block = $variant->getBlock($bid);

  // Get block settings.
  if ($block) {
    $settings = $block->getConfiguration();
  }
  $form['settings']['cache']['esi'] = array(
    '#type' => 'checkbox',
    '#title' => t('ESI block'),
    '#default_value' => $settings['cache']['esi'] ?: FALSE,
  );

}

/**
 * Implements hook_block_view_alter().
 */
function advanced_varnish_cache_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  //$build['#theme'] = 'advanced_varnish_cache_esi_block';
}

/**
 * Implements hook_theme().
 */
function advanced_varnish_cache_theme() {
  return array(
    'advanced_varnish_cache_esi_block' => array(
      'render element' => 'elements',
    ),
  );
}

/**
 * Implements template_preprocess_advanced_varnish_cache_esi_block().
 */
function template_preprocess_advanced_varnish_cache_esi_block(&$variables) {
  $elements = &$variables['elements'];
  $maxwait = 5000;
  $path = '/advanced_varnish_cache/esi/block/' . $elements['#id'];
  $url = Url::fromUserInput($path);
  $tag = "<!--esi\n" . '<esi:include src="' . $url->toString()  . '" maxwait="' . $maxwait . '"/>' . "\n-->";

  $variables['content'] = $tag;
}
